# Generated by Django 5.2.9 on 2026-03-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_networkdevice_password'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='users', to='devices.classroom'),
        ),
    ]
