# Generated by Django 5.2.9 on 2026-05-20 08:27

import apps.devices.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('is_internet_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', apps.devices.fields.EncryptedCharField(max_length=255)),
                ('api_port', models.IntegerField(default=8728)),
            ],
        ),
        migrations.CreateModel(
            name='AllowedHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowed_hosts', to='devices.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('hostname', models.CharField(max_length=100)),
                ('switch_port', models.CharField(default=' ', max_length=50)),
                ('is_online', models.BooleanField(default=False)),
                ('is_internet_blocked', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.classroom')),
                ('connected_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.networkdevice')),
            ],
        ),
    ]
