# Generated by Django 5.2.8 on 2025-11-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(default='1.1.1.1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='mac',
            field=models.CharField(default='00:00:00:00:00', max_length=17, unique=True),
            preserve_default=False,
        ),
    ]
