# Generated by Django 5.2.8 on 2025-11-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_ip_device_mac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='group',
            new_name='groups',
        ),
    ]
